### 监听 promise 以外的所有异常

```javascript
window.onerror = function (e) {};

window.addEventListener("error", function (e) {});
```

### 监听 promise 异常

<!-- 全局监听 unhandledrejection 事件来捕获未被处理的 Promise 错误 -->

```javascript

window.addEventListener("unhandledrejection", function (e) {});

```


```javascript

function getData() {
  return new Promise((resolve, reject) => {
    // 模拟一个异步操作
    setTimeout(() => {
      // 模拟一个错误
      const error = new Error("Something went wrong");
      reject(error);
    }, 2000);
  });
}

// 使用 catch 方法捕获 Promise 错误
getData()
  .then((data) => {
    // 在 resolve 时执行的操作
    console.log(data);
  })
  .catch((error) => {
    // 在 reject 时执行的操作
    console.error(error);
  });

// 全局监听 unhandledrejection 事件来捕获未被处理的 Promise 错误
window.addEventListener("unhandledrejection", (event) => {
  // 捕获未被处理的 Promise 错误
  console.error(event.reason);
});

```
